name: Android Internal Builds

# This workflow is setup to make Android builds and upload them to Buildy.io

# Controls when the action will run. 
on:
  workflow_dispatch:

env:
    UNITY_EMAIL: ${{ secrets.UNITY_EMAIL }}
    UNITY_PASSWORD: ${{ secrets.UNITY_PASSWORD }}
    UNITY_SERIAL: ${{ secrets.UNITY_SERIAL }}
    UPM_AUTH: ${{ secrets.UPM_AUTH }}
    BUILDY_BUCKET: ${{ secrets.AWS_BUILDY_BUCKET }}
    BUILD_NAME: MatchBox
    TARGET: Android #options(Android, iOS)
    STABILITY: Develop #options (Develop, Release)
    FAKE_BUILD: ${{ false }} #if true will skip the builder process, this is useful to debug other actions faster.

jobs:
  build:
    name: Build Unity Project
    runs-on: ubuntu-latest
    steps:
      # Checkout
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          token: ${{ secrets.PRIVATE_REPO_ACCESS_TOKEN }}
          submodules: 'true'
          lfs: 'true'

      # Cache
      - uses: actions/cache@v2.1.3
        with:
          path: Library
          key: ${{ github.workflow }}-Library-${{ github.sha }}
          restore-keys: |
            ${{ github.workflow }}-Library
      # Sets up the NPM registry authentication for the Unity Package Manager.
      - name: Set UPM auth
        shell: bash
        run: |
          mkdir $RUNNER_TEMP/_github_home
          touch $RUNNER_TEMP/_github_home/.upmconfig.toml
          echo "$UPM_AUTH" > $RUNNER_TEMP/_github_home/.upmconfig.toml
      
      # Build
      - name: Unity - Builder
        if: env.FAKE_BUILD == 'false' 
        id: builder
        uses: hdalaq/unity-builder@activation-import-fix
        with:
          buildName: ${{ env.BUILD_NAME }}-${{ env.STABILITY }}
          targetPlatform: ${{ env.TARGET }}
          buildMethod: Envelope.Builder.Editor.CI.Build
          customParameters: '-preprocessId CiSandboxDev-Android -Development'
      
      - name: Unity - Builder - Fake
        if: env.FAKE_BUILD == 'true'
        run: |
          mkdir -p build/Android
          touch build/Android/$BUILD_NAME.apk
          
      - name: Append - Version
        if: env.FAKE_BUILD == 'false'
        shell: bash
        run: |
          for x in build/Android/*; do sudo mv "$x" "${x%.*}-${BUILD_VERSION}.${x##*.}"; done
        env:
          BUILD_VERSION: ${{ steps.builder.outputs.buildVersion }}

      # Configures AWS credentials for AWS CLI.
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1
      
      - name: Upload to Buildy
        uses: playdots/buildy-uploader-action@master
        with:
          build-directory: $DIR
        env:
          DIR: ${{ format('build/{0}', env.TARGET) }}